# Site settings
site: www.ebenimeli.org
title: Enrique Benimeli
keywords: ebenimeli, blog
description: >- 
  Enrique Benimeli - web personal
lang: es-ES
timezone:  Europe/Madrid
#repo: https://github.com/onepase/Ephesus # site repo [optional]
#google_verify:      XXX # Put your Google Verification here
#google_analytics:   UA-XXXXXXXX-00 # Put your Google Analytics code
#discus-identifier:  XXX

# Author settings
author:
  name: Enrique Benimeli
  bio: Informática · Educación<br/>Productividad · Lenguas
  picture: assets/images/profile_books.jpg
  github: ebenimeli # github username
  twitter: enriquebenimeli # twitter username
  facebook: ebenimeli # facebook username
  instagram: ebenimeli # instagram username
  youtube: https://www.youtube.com/channel/UCcySEWq1InM_rbsvJY84zfQ # youtube username
  linkedin: ebenimeli # linkedin username
  substack: ebenimeli
  #email: your-email@email.com # email adress

# URL settings
url: "https://www.ebenimeli.org" # Domain Name of host. [username].github.io for github pages
#url: "http://localhost:4000" # Domain Name of host. [username].github.io for github pages

#url: "http://www.ebenimeli.org/beta" # Domain Name of host. [username].github.io for github pages

permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  - site/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links
paginate: 20
paginate_path: "/page/:num"

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false

collections:
  books:
    output: true
    permalink: /books/:title/
  logs:
    output: true
  pages:
    output: true
    permalink: /pages/:title
